export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const SHOW_ME_BEGIN = 'SHOW_ME_BEGIN'
export const SHOW_ME_SUCCESS = 'SHOW_ME_SUCCESS'
export const SHOW_ME_ERROR = 'SHOW_ME_ERROR'

export const LOGOUT_USER_BEGIN = 'LOGOUT_USER_BEGIN'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'

export const GET_ALL_USERS_BEGIN = 'GET_ALL_USERS_BEGIN'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'

export const DISPLAY_MODAL = 'DISPLAY_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_CHANGE_SELECT = 'HANDLE_CHANGE_SELECT'

export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const GET_ALL_PROJECTS_BEGIN = 'GET_ALL_PROJECTS_BEGIN'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'
export const GET_ALL_PROJECTS_ERROR = 'GET_ALL_PROJECTS_ERROR'

export const GET_ALL_TICKETS_BEGIN = 'GET_ALL_TICKETS_BEGIN'
export const GET_ALL_TICKETS_SUCCESS = 'GET_ALL_TICKETS_SUCCESS'
export const GET_ALL_TICKETS_ERROR = 'GET_ALL_TICKETS_ERROR'

export const GET_SINGLE_PROJECT_BEGIN = 'GET_SINGLE_PROJECT_BEGIN'
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS'
export const GET_SINGLE_PROJECT_ERROR = 'GET_SINGLE_PROJECT_ERROR'

export const GET_SINGLE_USER_BEGIN = 'GET_SINGLE_USER_BEGIN'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR'

export const UPDATE_ADD_MEMBER_TO_PROJECT_BEGIN =
  'UPDATE_ADD_MEMBER_TO_PROJECT_BEGIN'
export const UPDATE_ADD_MEMBER_TO_PROJECT_SUCCESS =
  'UPDATE_ADD_MEMBER_TO_PROJECT_SUCCESS'
export const UPDATE_ADD_MEMBER_TO_PROJECT_ERROR =
  'UPDATE_ADD_MEMBER_TO_PROJECT_ERROR'

export const CREATE_TICKET_BEGIN = 'CREATE_TICKET_BEGIN'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR'

export const DELETE_TICKET_BEGIN = 'DELETE_TICKET_BEGIN'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_ERROR = 'DELETE_TICKET_ERROR'

export const GET_TICKET_BEGIN = 'GET_TICKET_BEGIN'
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'
