export const CREATE_PROJECT_BEGIN = 'CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_ERROR = 'CREATE_PROJECT_ERROR'

export const GET_ALL_PROJECTS_BEGIN = 'GET_ALL_PROJECTS_BEGIN'
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS'
export const GET_ALL_PROJECTS_ERROR = 'GET_ALL_PROJECTS_ERROR'

export const GET_SINGLE_PROJECT_BEGIN = 'GET_SINGLE_PROJECT_BEGIN'
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS'
export const GET_SINGLE_PROJECT_ERROR = 'GET_SINGLE_PROJECT_ERROR'

export const UPDATE_ADD_MEMBER_TO_PROJECT_BEGIN =
  'UPDATE_ADD_MEMBER_TO_PROJECT_BEGIN'
export const UPDATE_ADD_MEMBER_TO_PROJECT_SUCCESS =
  'UPDATE_ADD_MEMBER_TO_PROJECT_SUCCESS'
export const UPDATE_ADD_MEMBER_TO_PROJECT_ERROR =
  'UPDATE_ADD_MEMBER_TO_PROJECT_ERROR'

export const HANDLE_CHANGE_SELECT = 'HANDLE_CHANGE_SELECT'
export const HANDLE_CHANGE_INPUT = 'HANDLE_CHANGE_INPUT'
