export const GET_ALL_TICKETS_BEGIN = 'GET_ALL_TICKETS_BEGIN'
export const GET_ALL_TICKETS_SUCCESS = 'GET_ALL_TICKETS_SUCCESS'
export const GET_ALL_TICKETS_ERROR = 'GET_ALL_TICKETS_ERROR'

export const CREATE_TICKET_BEGIN = 'CREATE_TICKET_BEGIN'
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS'
export const CREATE_TICKET_ERROR = 'CREATE_TICKET_ERROR'

export const DELETE_TICKET_BEGIN = 'DELETE_TICKET_BEGIN'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_ERROR = 'DELETE_TICKET_ERROR'

export const GET_TICKET_BEGIN = 'GET_TICKET_BEGIN'
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS'
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR'

export const UPDATE_TICKET_BEGIN = 'UPDATE_TICKET_BEGIN'
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS'
export const UPDATE_TICKET_ERROR = 'UPDATE_TICKET_ERROR'
