export const GET_ALL_USERS_BEGIN = 'GET_ALL_USERS_BEGIN'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'

export const GET_SINGLE_USER_BEGIN = 'GET_SINGLE_USER_BEGIN'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR'

export const DELETE_USER_BEGIN = 'DELETE_USER_BEGIN'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

export const UPDATE_USER_BY_ADMIN_BEGIN = 'UPDATE_USER_BY_ADMIN_BEGIN'
export const UPDATE_USER_BY_ADMIN_SUCCESS = 'UPDATE_USER_BY_ADMIN_SUCCESS'
export const UPDATE_USER_BY_ADMIN_ERROR = 'UPDATE_USER_BY_ADMIN_ERROR'
